export { default as HeroSlider } from './HeroSlider/HeroSlider'
export { default as Navbar } from './Navbar/Navbar'
export { default as Advantages } from './Advantages/Advantages'
export { default as About } from './About/About'
export { default as Trand } from './Trand/Trand'
export { default as Promo } from './Promo/Promo'
export { default as Contacts } from './Contacts/Contacts'
